export const siteConfig = {
  name: "Taariq Elliott",
  title: "Software Engineer & Creative Technologist",
  description: "Portfolio website of Taariq Elliott",
  accentColor: "#f29500",
  social: {
    email: "codebytaariq@gmail.com",
    linkedin: "https://linkedin.com/in/taariq-elliott",
    twitter: "https://taariqelliott.dev",
    github: "https://github.com/taariqelliott",
  },
  aboutMe:
    "I’m a Full-Stack Software Engineer with experience in JavaScript/TypeScript, Java, Python, and modern frameworks like React, Next.js, SvelteKit & Spring Boot. I’ve built applications ranging from live-streaming platform wrappers to interactive music theory tools, with a focus on delivering impactful, user-friendly experiences. I also bring a creative background as a music educator/producer, which fuels my problem-solving and collaborative approach to software development.",
  skills: [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "HTML",
    "CSS",
    "Spring Boot",
    "Next.js",
    "Svelte/SvelteKit",
    "Node.js",
    "Express",
    "React.js",
    "React Native",
    "Three.js",
    "React Three Fiber",
    "Electron",
    "p5.js",
    "Blender",
    "Flask",
    "Tailwind CSS",
    "shadcn/ui",
    "Git",
    "Neo4J",
    "Docker",
    "AWS (Bedrock, S3)",
    "Graph RAG",
    "Supabase",
    "MongoDB",
    "PostgreSQL",
    "SQLite/Better-SQLite3",
    "RESTful API",
    "JIRA",
  ],
  projects: [
    {
      name: "Friquency Radio",
      description:
        "Built and deployed a public social listening platform with Next.js, React, TypeScript, and Supabase, featuring media uploads, real-time chat, and interactive rooms.",
      link: "https://www.friquencyradio.com/",
      image: "/images/friquency.jpeg",
      skills: ["Next.js", "React", "Supabase", "Mantine UI"],
    },
    {
      name: "CrateKeeper",
      description:
        "Full-stack vinyl record collection manager with a FastAPI/PostgreSQL backend and Next.js frontend. Features album artwork uploads via Cloudinary, and search/filter by artist, genre, label, format, and condition.",
      link: "https://cratekeeper.vercel.app/",
      image: "/images/cratekeeper.jpeg",
      skills: [
        "Next.js",
        "React",
        "TypeScript",
        "FastAPI",
        "PostgreSQL",
        "SQLAlchemy",
        "Cloudinary",
        "Tailwind CSS",
        "shadcn/ui",
      ],
    },
    {
      name: "Ugubhu",
      description:
        "Born from my love of music and nostalgia for the legendary Winamp player, Ugubhu aims to bring back the magic of dedicated music playback and visualizations. Built with Electron, React, and Howler.js, it offers waveform displays via WaveSurfer.js, rich metadata parsing, custom color controls, looping, muting, and precise playback management. Actively developing: local file storage for offline libraries, playlist creation for organizing albums or groups of songs, and a sleeker, more intuitive UI for music lovers.",
      link: "https://github.com/taariqelliott/ugubhu-v1",
      image: "/images/ugubhu.jpeg",
      skills: [
        "Electron",
        "React",
        "TypeScript",
        "Howler.js",
        "WaveSurfer.js",
        "music-metadata",
        "HeroUI",
        "Tailwind",
      ],
    },
    {
      name: "Chromaphone",
      description:
        "Built an interactive audiovisual instrument with React, Three.js, React Three Fiber, and Tone.js that lets users play a 25-note 3D keyboard with both mouse and keyboard input. Combined sampled audio, animated key interactions, and real-time visual effects to create an immersive sound-and-color experience in the browser.",
      link: "https://chromaphone.onrender.com/",
      image: "/images/chromaphone.jpeg",
      skills: [
        "React",
        "TypeScript",
        "Three.js",
        "React Three Fiber",
        "Tone.js",
      ],
    },
    {
      name: "Theory Thing",
      description:
        "Interactive music theory app built with React and Tone.js. Provides real-time visual representations of chords and scales based on user-selected root notes and scale types.",
      link: "https://theorything.vercel.app/",
      image: "/images/theorything.jpeg",
      skills: ["React", "Tone.js", "JavaScript", "shadcn/ui"],
    },
  ],
  experience: [
    {
      company: "The Marcy Lab",
      title: "Mentor",
      dateRange: "Jan 2026 - Present",
      bullets: [
        "Mentoring an early-career engineer in creative coding with p5.js and Three.js, with a focus on generative art, interactive visuals, and animation.",
        "Supporting portfolio development through code reviews, pair programming, project feedback, and practical workflows that simulate real engineering collaboration.",
        "Coaching on broader software engineering fundamentals, including Git branches, communication, resume and LinkedIn reviews, networking, and choosing tech stacks that align with personal interests and long-term career goals.",
      ],
    },
    {
      company: "Booz Allen Hamilton",
      title: "Software Engineering Intern",
      dateRange: "Jul 2024 - Dec 2024",
      bullets: [
        "Developed a code modernization tool using Spring Boot, Spring Integration, Spring AI, and Spring Data.",
        "Integrated Neo4j to map and visualize complex code relationships.",
        "Implemented Docker for containerized development environments.",
      ],
    },
    {
      company: "Hip-Hop For Change",
      title: "Music Educator & Program Instructor",
      dateRange: "Aug 2022 - Feb 2024",
      bullets: [
        "Designed and delivered Hip-Hop music education programs across Los Angeles County.",
        "Secured $5,000+ in LAUSD grants through proposals to expand Hip-Hop curricula.",
        "Fostered creativity and self-expression in underserved students.",
      ],
    },
  ],
  education: [
    {
      school: "Build Carolina",
      degree: "Software Engineering Apprenticeship",
      dateRange: "Jul 2024 - Dec 2024",
      achievements: [
        "Completed apprenticeship curriculum and participated in technical discussions and professional workflows.",
        "Partnered with host company Booz Allen Hamilton while building and presenting a personal full-stack project as well as contributing to apprenticeship activities.",
      ],
    },
    {
      school: "General Assembly",
      degree: "Software Engineering Immersive",
      dateRange: "Dec 2022 - Jun 2023",
      achievements: [
        "Completed 500+ hours of expert-led instruction in full-stack web development.",
        "Gained hands-on experience with JavaScript, Python, MongoDB, Node.js, React, and PostgreSQL.",
      ],
    },
    {
      school: "Louisiana State University",
      degree: "B.S. in Marketing(Business) ",
      dateRange: "Aug 2011 - May 2016",
      achievements: [],
    },
  ],
};
